// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using komikaan.Harvester.Contexts;

#nullable disable

namespace komikaan.Harvester.Migrations
{
    [DbContext(typeof(GTFSContext))]
    [Migration("20240311153059_DateOffesets")]
    partial class DateOffesets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GTFS.Entities.Agency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FareURL")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("agencies");
                });

            modelBuilder.Entity("GTFS.Entities.Calendar", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<byte>("Mask")
                        .HasColumnType("smallint");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("ServiceId");

                    b.ToTable("calenders");
                });

            modelBuilder.Entity("GTFS.Entities.CalendarDate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("calendar_dates");
                });

            modelBuilder.Entity("GTFS.Entities.Frequency", b =>
                {
                    b.Property<string>("EndTime")
                        .HasColumnType("text");

                    b.Property<bool?>("ExactTimes")
                        .HasColumnType("boolean");

                    b.Property<string>("HeadwaySecs")
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .HasColumnType("text");

                    b.Property<string>("TripId")
                        .HasColumnType("text");

                    b.ToTable("frequencies");
                });

            modelBuilder.Entity("GTFS.Entities.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AgencyId")
                        .HasColumnType("text");

                    b.Property<int?>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LongName")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int?>("TextColor")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("GTFS.Entities.Stop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ParentStation")
                        .HasColumnType("text");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("WheelchairBoarding")
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stops");
                });

            modelBuilder.Entity("GTFS.Entities.StopTime", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("text");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text");

                    b.Property<int?>("DropOffType")
                        .HasColumnType("integer");

                    b.Property<int?>("PickupType")
                        .HasColumnType("integer");

                    b.Property<double?>("ShapeDistTravelled")
                        .HasColumnType("double precision");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("text");

                    b.Property<string>("StopId")
                        .HasColumnType("text");

                    b.Property<long>("StopSequence")
                        .HasColumnType("bigint");

                    b.Property<int>("TimepointType")
                        .HasColumnType("integer");

                    b.Property<string>("TripId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("stop_times");
                });

            modelBuilder.Entity("GTFS.Entities.Transfer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FromStopId")
                        .HasColumnType("text");

                    b.Property<string>("MinimumTransferTime")
                        .HasColumnType("text");

                    b.Property<string>("ToStopId")
                        .HasColumnType("text");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("transfers");
                });

            modelBuilder.Entity("GTFS.Entities.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("AccessibilityType")
                        .HasColumnType("integer");

                    b.Property<string>("BlockId")
                        .HasColumnType("text");

                    b.Property<int?>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("Headsign")
                        .HasColumnType("text");

                    b.Property<string>("RouteId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<string>("ShapeId")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("trips");
                });
#pragma warning restore 612, 618
        }
    }
}
